id: uplink-bots
url: "http://uplink-botservice:7891"
as_token: "e2045234fb0455c629524ee4d014d169e7ba3e0980ba21405a5251ca8a7ab47d"
hs_token: "92b719f6ea1a3f5c23509983e832a828d9b74eef8216f6977e42be155af73937"
sender_localpart: "botservice"
namespaces:
  users:
    - exclusive: true
      regex: "@bot_.*:uplink\\.local"
    - exclusive: false
      regex: "@.*:uplink\\.local"
  aliases: []
  rooms: []
rate_limited: false
