id: uplink-bots
url: "http://uplink-botservice:7891"
as_token: "157e2974361695922c937f0f2f328e73229a2984741fe962ec30dcf8dfec68b6"
hs_token: "dd77805f1f2d8ac2ffe4438e337d02af1237ee40595c9b9f7410e5d546a7551a"
sender_localpart: "botservice"
namespaces:
  users:
    - exclusive: true
      regex: '@bot_.*:uplink\.wh-lab\.ru'
    - exclusive: false
      regex: '@.*:uplink\.wh-lab\.ru'
  aliases: []
  rooms: []
rate_limited: false
